config/routes.rb
Brk2013::Application.routes.draw do

  get "static_pages/home"

  get "static_pages/guru_yoga"

  get "static_pages/karma_paksi"

  get "static_pages/programs"

  get "static_pages/information"

  root :to => 'static_pages#home'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get "sessions/new"

  scope ":locale" do
    resources :users
    resources :children
    resources :registrations
    resources :meals do
      resources :meal_report
    end
    resources :programs
    resources :payments
    resources :travels do
      resources :travel_report
    end
    resources :sessions
  end

  

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  

end

app/models/person.rb
class Person < ActiveRecord::Base

  has_many :meals
  has_many :registrations, :dependent => :destroy
  has_many :programs, :through => :registrations
  has_many :children
  has_many :travels

  attr_accessible :email_address, :first_name, :home_country, :payment, :phone_number, :price_category, :price_method, :reference_number, :second_name, :meals_attributes, :registrations_attributes, :children_attributes, :travels_attributes
  
  validate :first_name, :second_name, :home_country, :email_address, :payment, :price_method, :presence => true
  
  accepts_nested_attributes_for :meals, :allow_destroy => true
  accepts_nested_attributes_for :registrations, :allow_destroy => true
  accepts_nested_attributes_for :travels, :allow_destroy => true
  accepts_nested_attributes_for :children, :allow_destroy => true
  

  def reference_it
  	self.reference_number = self.first_name[0,1].to_s
  	self.reference_number += self.second_name[0,1].to_s
  	def random_alphanumeric(size=16)
  		chars = ('0'..'9').to_a + ('A'..'Z').to_a
  		(0...size).collect { chars[Kernel.rand(chars.length)] }.join
  	end
	  self.reference_number += random_alphanumeric(6)
  end

  before_save :reference_it
end

app/views/people/_child_fields.html.haml
= f.semantic_fields_for :children do |child|
  =child.input :name
  =child.input :age
  =child.input :language
  =child.input :child_care, as: :boolean
  %table
    %tr
      %th= Meal.human_attribute_name(:meal_date)
      %th= Meal.human_attribute_name(:food_type)
      %th= Meal.human_attribute_name(:meal_type)
    -@meal_dates.each do |meal_date|
      =f.semantic_fields_for :meals do |ff|
        %tr
          %td= meal_date
          %td= ff.input :food_type
          %td= ff.input :meal_type, as: :select, collection: [['Lunch', 1], ['Three Meals', 3], ['None', nil]]
  =child.link_to_remove "Remove child", class: 'btn btn-danger'

app/views/people/_form.html.erb
<%= nested_form_for @person do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :second_name %><br />
    <%= f.text_field :second_name %>
  </div>
  <div class="field">
    <%= f.label :home_country %><br />
    <%= f.select :home_country, options_for_select(@countries) %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br />
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :email_address %><br />
    <%= f.text_field :email_address %>
  </div>
  <div class="field">
    <%= f.label :price_category %><br />
    <%= f.select(:price_category, [['full', 'full'], ['support', 'support'], ['escort', 'escort'], ['discount', 'discount']]) %>
  </div>
  <div class="field">
    <%= f.label :price_method %><br />
    <%= f.select(:price_method, [['helyszínen', 'course'], ['előre utal', 'bank'],['előre készpénz', 'cash']]) %> 
  </div>
  <div class="field">
    <%= f.label :payment %><br />
    <%= f.text_field :payment %>
  </div>
  <h2><%= t 'meals' %></h2>
  <table>
  <tr>
  <th><%= f.label :meal_date %></th>
  <th><%= f.label :food_type %></th>
  <th><%= f.label :meal_type %></th>
  </tr>
  <% @meal_dates.each do |meal_date| %>
    <%= f.fields_for :meals do |f2| %>
    <tr>
    <td><%= f2.text_field :meal_date, :value => meal_date %></td>
    <td><%= f2.hidden_field :food_type, :class => 'FoodType', :value => 'vegetarian'%></td>
    <td><%= f2.select(:meal_type, [['Lunch', 1], ['Three Meals', 3], ['None', nil]]) %></td>
    </tr>
    <% end %>
  <% end %>
  </table>
  <%= f.link_to_add 'Add another Meal', :meals %>
  <h2><%= t 'children' %></h2>
  <%= f.fields_for :children do |builder| %>
    <%= render 'child_fields', f: builder %>
  <% end %>
  <%= f.link_to_add 'Add Children', :children %>
  <h2><%= t 'registrations' %></h2>
  <table>
  <tr>
    <th><%= Program.human_attribute_name(:event_date) %></th>
    <th><%= Program.human_attribute_name(:program_name_hu) %></th>
    <th><%= Program.human_attribute_name(:program_name_en) %></th>
    <th><%= Program.human_attribute_name(:price_full) %></th>
    <th><%= Program.human_attribute_name(:price_member) %></th>
    <th><%= Program.human_attribute_name(:price_discount) %></th>
    <th></th>
  </tr>
<% @programs.each do |program| %>
  <tr>
    <td><%= program.event_date %></td>
    <td><%= program.program_name_hu %></td>
    <td><%= program.program_name_en %></td>
    <td><%= program.price_full %></td>
    <td><%= program.price_member %></td>
    <td><%= program.price_discount %></td>
    <td>
    <%= f.fields_for :registrations do |f| %>
      <%= f.check_box :participate %>
      <%= f.hidden_field :program_id, :value => program.id %>
    <% end %>
    </td>
  </tr>
<% end %>
</table> 
<h2><%= t 'travel' %></h2>
<p><%= t 'travel_description' %></p>
  <%= f.fields_for :travels do |travel| %>
  <fieldset>
  <div class="field">
    <%= travel.label :bus_trip %><br />
    <%= travel.check_box :bus_trip %>
  </div>
  <div class="field">
    <%= travel.label :arrival %><br />
    <%= travel.select(:arrival, [['2013-07-12 11:00', '2013-07-12 11:00'], ['2013-07-12 11:00', '2013-07-12 15:00']]) %>
  </div>
  <div class="field">
    <%= travel.label :arrival_seats %><br />
    <%= travel.select(:arrival_seats, (0...6)) %>
  </div>
  <div class="field">
    <%= travel.label :departure %><br />
    <%= travel.select(:departure, [['2013-07-18 20:00', '2013-07-18 20:00'],['2013-07-18 20:00', '2013-07-18 20:00']]) %>
  </div>
  <div class="field">
    <%= travel.label :departure_seats %><br />
    <%= travel.select(:departure_seats, (0...6)) %>
  </div>
  <div class="field">
    <%= travel.label :flight_date %><br />
    <%= travel.datetime_select :flight_date %>
  </div>
  <div class="field">
    <%= travel.label :flight_number %><br />
    <%= travel.text_field :flight_number %>
  </div>
  </fieldset>
  <% end %>
    <%= f.hidden_field :reference_number %>
  <div class="actions">
    <%= f.submit :class => 'RegistrationButton' =%>
  </div>
  <% end %>

app/views/people/_form.html.haml
= semantic_nested_form_for @person do |f|
  =f.inputs 'Alap Adatok', id: 'basic' do
    =f.input :first_name
    =f.input :second_name
    =f.input :home_country
    =f.input :phone_number
    =f.input :email_address
    =f.input :price_category, collection: [['full', 'full'], ['support', 'support'], ['escort', 'escort'], ['discount', 'discount']]
    =f.input :price_method, collection: [['helyszínen', 'course'], ['előre utal', 'bank'],['előre készpénz', 'cash']]
    =f.input :payment
  =f.inputs t 'meals', id: 'meals' do
    %table.table
      %tr
        %th= f.label :meal_date
        %th= f.label :food_type
        %th= f.label :meal_type
      - @meal_dates.each do |meal_date|
        = f.semantic_fields_for @meals do |meal|
          %tr
            %td= meal_date
            %td= meal.input :food_type
            %td= meal.input :meal_type, as: :select, collection: [['Lunch', 1], ['Three Meals', 3], ['None', nil]]
  =f.inputs t 'children', id: 'children' do
    = f.semantic_fields_for :children do |builder|
      = render 'child_fields', f: builder
      = f.link_to_add 'Add Children', :children, class: 'btn btn-warning'
  =f.inputs t 'registrations', id: 'registrations' do
    %table.table
      %tr
        %th= Program.human_attribute_name(:event_date)
        %th= Program.human_attribute_name(:program_name_hu)
        %th= Program.human_attribute_name(:program_name_en)
        %th= Program.human_attribute_name(:price_full)
        %th= Program.human_attribute_name(:price_member)
        %th= Program.human_attribute_name(:price_discount)
        %th
      - @programs.each do |program|
        %tr
          %td= program.event_date
          %td= program.program_name_hu
          %td= program.program_name_en
          %td= program.price_full
          %td= program.price_member
          %td= program.price_discount
          %td
            = f.fields_for :registrations do |f|
              = f.input :participate, as: :check_boxes
  =f.inputs t 'travel', id: 'travel' do
    %p= t 'travel_description'
    = f.fields_for :travels do |travel|
      = render 'travel_fields', f: travel
    = f.hidden_field :reference_number
  =f.actions class: 'btn btn-large btn-success'

app/views/people/_travel_fields.html.haml
= f.semantic_fields_for :travels do
  =f.input :bus_trip
  =f.input :arrival, as: :select, collection: [['2013-07-12 11:00', '2013-07-12 11:00'], ['2013-07-12 11:00', '2013-07-12 15:00']]
  =f.input :arrival_seats, as: :select, collection: (0...6)
  =f.input :departure, as: :select, collection: [['2013-07-18 20:00', '2013-07-18 20:00'],['2013-07-18 20:00', '2013-07-18 20:00']]
  =f.input :departure_seats, as: :select, collection: (0...6)
  =f.input :flight_date, as: :date
  =f.input :flight_number

app/views/people/index.html.haml
%h1 Listing people
.well
  = link_to 'New Person', new_person_path, class: 'btn btn-success btn-large'
%table.table.table-bordered.table-hover
  %tr
    %th First name
    %th Second name
    %th Home country
    %th Phone number
    %th Email address
    %th Price method
    %th Price category
    %th Payment
    %th Reference number
    %th
    %th
    %th
  - @people.each do |person|
    %tr
      %td= person.first_name
      %td= person.second_name
      %td= person.home_country
      %td= person.phone_number
      %td= person.email_address
      %td= person.price_method
      %td= person.price_category
      %td= person.payment
      %td= person.reference_number
      %td= link_to 'Show', person, class: 'btn'
      %td= link_to 'Edit', edit_person_path(person), class: 'btn'
      %td= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn'
%br/

app/views/people/new.html.haml
%h1= t 'sitename'
= render 'form'
= link_to 'Back', people_path

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @person.first_name %>
</p>

<p>
  <b>Second name:</b>
  <%= @person.second_name %>
</p>

<p>
  <b>Home country:</b>
  <%= @person.home_country %>
</p>

<p>
  <b>Phone number:</b>
  <%= @person.phone_number %>
</p>

<p>
  <b>Email address:</b>
  <%= @person.email_address %>
</p>

<p>
  <b>Price method:</b>
  <%= @person.price_method %>
</p>

<p>
  <b>Price category:</b>
  <%= @person.price_category %>
</p>

<p>
  <b>Payment:</b>
  <%= @person.payment %>
</p>
<p>
  <b>Reference number:</b>
  <%= @person.reference_number %>
</p>

<h3>Meals</h3>
<table>
  <tr>
    <th>Meal date</th>
    <th>Food type</th>
    <th>Meal type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @meals.each do |meal| %>
  <tr>
    <td><%= meal.meal_date %></td>
    <td><%= meal.food_type %></td>
    <td><%= meal.meal_type %></td>
    <td><%= link_to 'Show', meal %></td>
    <td><%= link_to 'Edit', edit_meal_path(meal) %></td>
    <td><%= link_to 'Destroy', meal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<h3>Children</h3>
<table>
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th>Language</th>
    <th>Child care</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @children.each do |child| %>
  <tr>
    <td><%= child.name %></td>
    <td><%= child.age %></td>
    <td><%= child.language %></td>
    <td><%= child.child_care %></td>
    <td><%= link_to 'Show', child %></td>
    <td><%= link_to 'Edit', edit_child_path(child) %></td>
    <td><%= link_to 'Destroy', child, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
    <table>
      <h4>Child's meals</h4>
      <tr>
        <th>Meal date</th>
        <th>Food type</th>
        <th>Meal type</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>

    <% child.meals.each do |meal| %>
      <tr>
        <td><%= meal.meal_date %></td>
        <td><%= meal.food_type %></td>
        <td><%= meal.meal_type %></td>
        <td><%= link_to 'Show', meal %></td>
        <td><%= link_to 'Edit', edit_meal_path(meal) %></td>
        <td><%= link_to 'Destroy', meal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </table>
<% end %>
</table>

<h2>Program Registration</h2>
<table>
  <tr>
    <th>Program id</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @registrations.each do |registration| %>
  <tr>
    <td><%= registration.program_id %></td>
    <td><%= link_to 'Show', registration %></td>
    <td><%= link_to 'Edit', edit_registration_path(registration) %></td>
    <td><%= link_to 'Destroy', registration, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<h3><%= t 'travel' %></h3>
<table>
  <tr>
    <th>Arrival</th>
    <th>Bus trip</th>
    <th>Arrival seats</th>
    <th>Departure seats</th>
    <th>Departure</th>
    <th>Flight number</th>
    <th>Flight date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @travels.each do |travel| %>
  <tr>
    <td><%= travel.arrival %></td>
    <td><%= travel.bus_trip %></td>
    <td><%= travel.arrival_seats %></td>
    <td><%= travel.departure_seats %></td>
    <td><%= travel.departure %></td>
    <td><%= travel.flight_number %></td>
    <td><%= travel.flight_date %></td>
    <td><%= link_to 'Show', travel %></td>
    <td><%= link_to 'Edit', edit_travel_path(travel) %></td>
    <td><%= link_to 'Destroy', travel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <% end %>
</table>

<br />

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>