config/routes.rb
Brk2013::Application.routes.draw do

  get "static_pages/home"

  get "static_pages/guru_yoga"

  get "static_pages/karma_paksi"

  get "static_pages/programs"

  get "static_pages/information"

  root :to => 'static_pages#home'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get "sessions/new"

  scope ":locale" do
    resources :users
    resources :children
    resources :registrations
    resources :meals do
      resources :meal_report
    end
    resources :programs
    resources :payments
    resources :travels do
      resources :travel_report
    end
    resources :sessions
  end

  

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/child.rb
class Child < ActiveRecord::Base
  belongs_to :user
  attr_accessible :age, :child_care, :language, :name, :user_id
  validate :age, :child_care, :language, :name, :presence => true
end

app/models/meal.rb
class Meal < ActiveRecord::Base
  belongs_to :user
  attr_accessible :fifth_day, :fifth_day_meal_type, :first_day, :first_day_meal_type, :food_type, :fourth_day, :fourth_day_meal_type, :second_day, :second_day_meal_type, :seventh_day, :seventh_day_meal_type, :sixth_day, :sixth_day_meal_type, :third_day, :third_day_meal_type
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :user
  attr_accessible :comment, :date, :amount, :user_id, :user_attributes

end

app/models/person.rb
class Person < ActiveRecord::Base

  has_many :meals
  has_many :registrations, :dependent => :destroy
  has_many :programs, :through => :registrations
  has_many :children
  has_many :travels

  attr_accessible :email_address, :first_name, :home_country, :payment, :phone_number, :price_category, :price_method, :reference_number, :second_name, :meals_attributes, :registrations_attributes, :children_attributes, :travels_attributes
  
  validate :first_name, :second_name, :home_country, :email_address, :payment, :price_method, :presence => true
  
  accepts_nested_attributes_for :meals, :allow_destroy => true
  accepts_nested_attributes_for :registrations, :allow_destroy => true
  accepts_nested_attributes_for :travels, :allow_destroy => true
  accepts_nested_attributes_for :children, :allow_destroy => true
  

  def reference_it
  	self.reference_number = self.first_name[0,1].to_s
  	self.reference_number += self.second_name[0,1].to_s
  	def random_alphanumeric(size=16)
  		chars = ('0'..'9').to_a + ('A'..'Z').to_a
  		(0...size).collect { chars[Kernel.rand(chars.length)] }.join
  	end
	  self.reference_number += random_alphanumeric(6)
  end

  before_save :reference_it
end

app/models/program.rb
class Program < ActiveRecord::Base
  attr_accessible :exchange_rate, :price_discount, :price_full, :price_full_eur, :price_discount_eur, :program_name_en, :program_name_hu, :event_date

  has_many :registrations
  has_many :users, :through => :registrations
end

app/models/registration.rb
class Registration < ActiveRecord::Base
  attr_accessible :user_id, :program_id, :participate

  belongs_to :user
  belongs_to :program

end

app/models/travel.rb
class Travel < ActiveRecord::Base  
  belongs_to :user
  attr_accessible :arrival, :arrival_seats, :bus_trip, :departure, :departure_seats, :flight_date, :flight_number, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  has_many :meals, :dependent => :destroy
  has_many :registrations, :dependent => :destroy
  has_many :programs, :through => :registrations
  has_many :children, :dependent => :destroy
  has_many :travels, :dependent => :destroy
  has_many :payments, :dependent => :destroy

  attr_accessible :email_address, :password, :password_confirmation, :first_name, :home_country, :payment, :phone_number, :price_category, :price_method, :reference_number, :second_name, :meals_attributes, :registrations_attributes, :children_attributes, :travels_attributes
  
  validates_presence_of :first_name, :second_name, :home_country, :email_address, :payment, :price_method, :price_category
  
  validates_uniqueness_of :reference_number
  
  accepts_nested_attributes_for :meals, :allow_destroy => true
  accepts_nested_attributes_for :registrations, :reject_if => proc { |attributes| attributes[:participate] == '0' }, :allow_destroy => true
  accepts_nested_attributes_for :children, :reject_if => proc { |attributes| attributes[:name] == '' }, :allow_destroy => true
  accepts_nested_attributes_for :travels, :reject_if => proc { |attributes| attributes[:bus_trip] == "0" && attributes[:flight_number] == "" }, :allow_destroy => true
  

  def reference_it
  	self.reference_number = self.first_name[0,1].to_s
  	self.reference_number += self.second_name[0,1].to_s
  	def random_alphanumeric(size=16)
  		chars = ('0'..'9').to_a + ('A'..'Z').to_a
  		(0...size).collect { chars[Kernel.rand(chars.length)] }.join
  	end
	  self.reference_number += random_alphanumeric(6)
    self.password = self.password_confirmation = self.reference_number
    self.password_digest = BCrypt::Password.create(reference_number).to_s
  end

  before_save :reference_it
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  @@selected_currency = ""
  
  def countries_list 
    I18n.t(:home_country).map { |key, value| [ value, key ] } 
  end
  
  def price_category_list
    I18n.t(:price_category).map { |key, value| [ value, key ] }
  end
  
  def price_method_list
    I18n.t(:price_method).map { |key, value| [ value, key ] }
  end
  def first_day_meal_type_list
    I18n.t(:first_day_meal_type).map { |key, value| [ value, key ] }
  end
  def second_day_meal_type_list
    I18n.t(:second_day_meal_type).map { |key, value| [ value, key ] }
  end
  def third_day_meal_type_list
    I18n.t(:third_day_meal_type).map { |key, value| [ value, key ] }
  end
  def fourth_day_meal_type_list
    I18n.t(:fourth_day_meal_type).map { |key, value| [ value, key ] }
  end
  def fifth_day_meal_type_list
    I18n.t(:fifth_day_meal_type).map { |key, value| [ value, key ] }
  end
  def sixth_day_meal_type_list
    I18n.t(:sixth_day_meal_type).map { |key, value| [ value, key ] }
  end
  def seventh_day_meal_type_list
    I18n.t(:seventh_day_meal_type).map { |key, value| [ value, key ] }
  end
  def food_type_list
    I18n.t(:food_type).map { |key, value| [ value, key ] }
  end
  def show_meal_type(meal_type)
      if meal_type.to_i == 1
        t 'lunch'
      elsif meal_type.to_i == 3
        t 'three_time'
      else
        t 'no_food'
      end
  end
  def show_food_type(food_type)
      if food_type == "vegetarian"
        t 'vegetarian'
      else
        t 'meat'
      end
  end
  def show_child_care(child_care)
      if child_care == true
        t 'child_care_true'
      else
        t 'child_care_false'
      end
  end
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/travels_helper.rb
module TravelsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t 'sitename' %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag :defaults, "nested_form" %>
    <%= csrf_meta_tag %>
  </head>
  <body class="<%= controller.controller_name %> <%= controller.action_name %>">
    <div class="red-line">
      <%= link_to_unless_current image_tag("english_flag.png"), locale: "en" %>
      <%= link_to_unless_current image_tag("hungarian_flag.png"), locale: "hu" %>
    </div>
    <div class="logo"><%= image_tag("diamond-way-logo.png")%></div>
    <div id="container">
      <% unless @menu_enabled != true %>
          <div class="navbar">
            <div class="navbar-inner">
            <ul class="nav">
            <li><%= link_to t('activerecord.controllers.static_pages.home.menu_title'), :controller => :static_pages, :action => :home %></li>
            <li><%= link_to t('activerecord.controllers.static_pages.guru_yoga.menu_title'), :controller => :static_pages, :action => :guru_yoga %></li>
            <li><%= link_to t('activerecord.controllers.static_pages.karma_paksi.menu_title'), :controller => :static_pages, :action => :karma_paksi %></li>
            <li><%= link_to t('activerecord.controllers.static_pages.information.menu_title'), :controller => :static_pages, :action => :information %></li>
            <li><%= link_to t('activerecord.controllers.static_pages.programs.menu_title'), :controller => :static_pages, :action => :programs %></li>
            <li><%= link_to t('registration'), :controller => :users, :action => :new %></li>
            </ul>
            </div>
          </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= t 'sitename'
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tag
  %body
    %header.navbar.navbar-fixed-top
      .navbar-inner
        .container
          =link_to "HOME", root_path, class: 'brand'
          %ul.nav.pull-left
            %li=link_to "People", people_path
            %li=link_to "Children", children_path
            %li=link_to "Programs", programs_path
            %li=link_to "Registrations", registrations_path
            %li=link_to "Travels", travels_path
          %ul.nav.pull-righ
            %li= link_to "English", locale: "en"
            %li= link_to "Magyar", locale: "hu"


    .container
      -flash.each do |name, msg|
        - if msg.is_a?(String)
          %div{class: "alert alert-#{name == :notice ? "success" : "error"}"}
            %a.close{data: {dismiss: 'alert'}} ×
            =content_tag :div, msg, id: "flash_#{name}"
    .container
      = yield